use std::fs;
use std::io::Write;
use std::path::Path;
use winres::WindowsResource;
use anyhow::{Context, Result};

fn xor_encrypt(data: &str, key: u8) -> Vec<u8> {
    data.bytes()
        .enumerate()
        .map(|(i, b)| b ^ key.wrapping_add(i as u8))
        .collect()
}

fn format_bytes_array(bytes: &[u8]) -> String {
    let byte_strs: Vec<String> = bytes.iter().map(|b| format!("{}", b)).collect();
    format!("&[{}]", byte_strs.join(", "))
}

fn main() -> Result<()> {
    let config_path = Path::new("src/config.rs");
    let config_content = fs::read_to_string(config_path).context("Failed to read src/config.rs")?;

    let get_val = |key| {
        config_content
            .lines()
            .find(|line| line.trim().starts_with(&format!("{}:", key)))
            .and_then(|line| line.split(':').nth(1))
            .and_then(|val| {
                let cleaned = val.split("//").next().unwrap_or(val);
                Some(cleaned.trim().trim_matches(',').trim_matches('"'))
            })
            .unwrap_or("")
            .to_string()
    };

    let file_ver_str = get_val("file_version");
    let file_name_str = get_val("file_name");
    let product_name = get_val("product_name");
    let description = get_val("description");
    let company_name = get_val("company_name");

    let token = std::env::var("KURINIUM_TOKEN").unwrap_or_else(|_| {
        config_content
            .lines()
            .find(|line| line.contains("DISCORD_TOKEN"))
            .and_then(|line| {
                line.split('"')
                    .nth(1)
                    .map(|s| s.to_string())
            })
            .unwrap_or_else(|| "PLACEHOLDER_TOKEN".to_string())
    });

    let key: u8 = (std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs() % 256) as u8;
    
    let key = if key == 0 { 42 } else { key };

    let encrypted_bytes = xor_encrypt(&token, key);
    let encrypted_array = format_bytes_array(&encrypted_bytes);

    let out_dir = std::env::var("OUT_DIR").context("OUT_DIR not set")?;
    let token_path = Path::new(&out_dir).join("encrypted_token.rs");
    
    let generated_code = format!(
        r#"// Auto-generated by build.rs - DO NOT EDIT
// Token is XOR encrypted at compile time

/// Encrypted Discord token bytes
pub const ENCRYPTED_TOKEN: &[u8] = {};

/// Encryption key used for XOR
pub const ENCRYPTION_KEY: u8 = {};
"#,
        encrypted_array,
        key
    );
    
    fs::File::create(&token_path)
        .context("Failed to create encrypted_token.rs")?
        .write_all(generated_code.as_bytes())
        .context("Failed to write encrypted_token.rs")?;

    if cfg!(target_os = "windows") {
        let ver_parts: Vec<u64> = file_ver_str
            .split('.')
            .map(|s| s.parse::<u64>().unwrap_or(0))
            .collect();

        let file_ver_u64 = if ver_parts.len() == 4 {
            (ver_parts[0] << 48) | (ver_parts[1] << 32) | (ver_parts[2] << 16) | ver_parts[3]
        } else {
            0x0001000000000000
        };

        WindowsResource::new()
            .set_icon("assets/kurinium.ico")
            .set_version_info(winres::VersionInfo::FILEVERSION, file_ver_u64)
            .set_version_info(winres::VersionInfo::PRODUCTVERSION, file_ver_u64)
            .set("FileVersion", &file_ver_str)
            .set("ProductVersion", &file_ver_str)
            .set("ProductName", &product_name)
            .set("FileDescription", &description)
            .set("CompanyName", &company_name)
            .set("InternalName", &file_name_str) 
            .set("OriginalFilename", &file_name_str)
            .compile()?;
    }
    
    println!("cargo:rerun-if-changed=src/config.rs");
    println!("cargo:rerun-if-env-changed=KURINIUM_TOKEN");

    Ok(())
}